workflows:
  ios-build:
    name: Rawh iOS Build
    environment:
      flutter: stable
      xcode: latest
    instance_type: mac_mini_m2
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release --export-method development
    artifacts:
      - build/ios/ipa/*.ipa
    code_signing:
      automatic:
        distribution_type: development
        apple_provisioning_profile: automatic